#!/usr/bin/env python3

###
# Generates build.ninja and objdiff.json.
#
# This project decompiles the Dolphin Network Base Package socket library
# (ip) and dvdeth libraries. Every library ships in two flavors, a release
# build (<lib>.a) and a debug build (<lib>D.a), and both are matched from the
# same source.
#
# Usage:
#   python configure.py
#   ninja            # build all objects that have source
#   ninja progress   # print matching progress
#
# Re-run configure.py after adding a new source file.
###

import argparse
import json
import os
import platform
import sys
from io import StringIO
from pathlib import Path
from typing import Dict, List, Optional

sys.path.append(str(Path(__file__).parent / "tools"))
from ninja_syntax import Writer, serialize_path  # noqa: E402

ROOT = Path(__file__).parent.resolve()

# Libraries to build. Target objects are expected at
# baserom/{release,debug}/<lib>/<unit>.o (see tools/extract.py).
LIBS: List[str] = ["ip", "dvdeth"]

CONFIGS = {
    "release": {
        "suffix": "",
        "cflags": ["-O4,p", "-inline auto", "-DRELEASE"],
    },
    "debug": {
        "suffix": "D",
        "cflags": ["-opt level=0", "-inline off", "-schedule off", "-DDEBUG"],
    },
}

CFLAGS_BASE = [
    "-nodefaults",
    "-proc gekko",
    "-fp hard",
    "-char signed",
    "-lang=c",
    "-Cpp_exceptions off",
    "-enum int",
    "-warn pragmas",
    "-requireprotos",
    "-pragma \"cats off\"",
    "-sym on",
    "-I-",
    "-Idolphin/include/libc",
    "-Idolphin/include",
    "-ir src",
]

DTK_TAG = "v1.8.3"
OBJDIFF_TAG = "v3.8.1"
WIBO_TAG = "0.6.11"
COMPILER_VERSION = "GC/1.2.5n"


def is_windows() -> bool:
    return os.name == "nt"


EXE = ".exe" if is_windows() else ""
# ninja runs commands without a shell on Windows; chained commands need cmd.
CHAIN = "cmd /c " if is_windows() else ""


def cmd_path(path: Path) -> str:
    # cmd.exe needs native separators for the program path
    return str(path).replace("/", "\\") if is_windows() else serialize_path(path)


def find_units(lib: str) -> List[str]:
    units = set()
    for cfg in CONFIGS:
        target_dir = ROOT / "baserom" / cfg / lib
        if target_dir.is_dir():
            units.update(p.stem for p in target_dir.glob("*.o"))
    return sorted(units, key=str.lower)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compilers", type=Path, default=Path("mwcc_compiler"),
                        help="path to compilers directory (containing GC/1.2.5n)")
    parser.add_argument("--wrapper", type=Path,
                        help="wrapper for running Windows executables (default: wibo on non-Windows)")
    parser.add_argument("--dtk", type=Path, help="path to a local decomp-toolkit binary")
    parser.add_argument("--objdiff", type=Path, help="path to a local objdiff-cli binary")
    args = parser.parse_args()

    out = StringIO()
    n = Writer(out)
    n.comment("Generated by configure.py; do not edit.")
    n.newline()
    n.variable("ninja_required_version", "1.3")
    n.newline()

    python = sys.executable.replace("\\", "/")
    configure_args = " ".join(sys.argv[1:])
    build_tools = Path("build/tools")

    ###
    # Tools
    ###
    n.comment("Tools")
    n.rule(
        name="download_tool",
        command=f"{python} tools/download_tool.py $tool $out --tag $tag",
        description="TOOL $out",
    )
    n.newline()

    if args.dtk:
        dtk = args.dtk
    else:
        dtk = build_tools / f"dtk{EXE}"
        n.build(outputs=dtk, rule="download_tool", implicit="tools/download_tool.py",
                variables={"tool": "dtk", "tag": DTK_TAG})
        n.newline()

    if args.objdiff:
        objdiff = args.objdiff
    else:
        objdiff = build_tools / f"objdiff-cli{EXE}"
        n.build(outputs=objdiff, rule="download_tool", implicit="tools/download_tool.py",
                variables={"tool": "objdiff-cli", "tag": OBJDIFF_TAG})
        n.newline()

    wrapper: Optional[Path] = args.wrapper
    wrapper_implicit: List[Path] = []
    if wrapper is None and not is_windows():
        wrapper = build_tools / "wibo"
        n.build(outputs=wrapper, rule="download_tool", implicit="tools/download_tool.py",
                variables={"tool": "wibo", "tag": WIBO_TAG})
        n.newline()
        wrapper_implicit = [wrapper]
    wrapper_cmd = f"{serialize_path(wrapper)} " if wrapper else ""

    mwcc = args.compilers / COMPILER_VERSION / "mwcceppc.exe"

    ###
    # Rules
    ###
    n.comment("Compile C with MWCC; mwcc writes <basename>.d next to the object with -MD")
    n.rule(
        name="mwcc",
        command=(
            f"{CHAIN}{wrapper_cmd}{cmd_path(mwcc)} $cflags -MD -c $in -o $basedir"
            f" && {python} tools/transform_dep.py $basefile.d $basefile.d"
        ),
        description="MWCC $out",
        depfile="$basefile.d",
        deps="gcc",
    )
    n.newline()

    n.rule(
        name="ar",
        command=f"{python} tools/mkar.py $out $in",
        description="AR $out",
    )
    n.newline()

    n.rule(
        name="report",
        command=f"{cmd_path(objdiff)} report generate -o $out",
        description="REPORT",
    )
    n.newline()

    n.rule(
        name="progress",
        command=f"{python} tools/progress.py $in",
        description="PROGRESS",
    )
    n.newline()

    ###
    # Build statements
    ###
    objdiff_units: List[Dict] = []
    all_objects: List[str] = []
    lib_outputs: List[str] = []
    missing_targets: List[str] = []

    for lib in LIBS:
        units = find_units(lib)
        if not units:
            missing_targets.append(lib)
        for cfg, cfg_info in CONFIGS.items():
            lib_objects: List[str] = []
            n.comment(f"{lib}{cfg_info['suffix']}.a ({cfg})")
            cflags = " ".join(CFLAGS_BASE + cfg_info["cflags"])
            for unit in units:
                src = Path("src") / lib / f"{unit}.c"
                target = Path("baserom") / cfg / lib / f"{unit}.o"
                base = Path("build") / cfg / lib / f"{unit}.o"
                has_src = (ROOT / src).is_file()

                if has_src:
                    basedir = base.parent
                    n.build(
                        outputs=base,
                        rule="mwcc",
                        inputs=src,
                        implicit=[mwcc] + wrapper_implicit,
                        variables={
                            "cflags": cflags,
                            "basedir": serialize_path(basedir),
                            "basefile": serialize_path(basedir / unit),
                        },
                    )
                    lib_objects.append(serialize_path(base))
                    all_objects.append(serialize_path(base))

                unit_cfg = {
                    "name": f"{lib}{cfg_info['suffix']}/{unit}",
                    "target_path": serialize_path(target),
                    "metadata": {
                        "progress_categories": [lib, cfg],
                    },
                }
                if has_src:
                    unit_cfg["base_path"] = serialize_path(base)
                    unit_cfg["metadata"]["source_path"] = serialize_path(src)
                objdiff_units.append(unit_cfg)

            if lib_objects:
                archive = f"out/{lib}{cfg_info['suffix']}.a"
                n.build(outputs=archive, rule="ar", inputs=lib_objects, implicit="tools/mkar.py")
                lib_outputs.append(archive)
            n.newline()

    n.comment("Phony targets")
    n.build(outputs="objects", rule="phony", inputs=all_objects)
    n.build(outputs="libs", rule="phony", inputs=lib_outputs)
    n.newline()

    report = Path("build") / "report.json"
    n.build(outputs=report, rule="report", inputs=all_objects, implicit=[objdiff, "objdiff.json"])
    n.build(outputs="progress", rule="progress", inputs=report, implicit="tools/progress.py")
    n.newline()

    n.comment("Reconfigure on change")
    n.rule(
        name="configure",
        command=f"{python} configure.py {configure_args}".rstrip(),
        description="RUN configure.py",
        generator=True,
    )
    n.build(
        outputs=["build.ninja", "objdiff.json"],
        rule="configure",
        implicit=["configure.py", "tools/ninja_syntax.py"],
    )
    n.newline()

    n.default(["objects", "libs"])

    with open(ROOT / "build.ninja", "w", encoding="utf-8") as f:
        f.write(out.getvalue())

    objdiff_config = {
        "min_version": "2.0.0",
        "custom_make": "ninja",
        "build_target": False,
        "build_base": True,
        "watch_patterns": [
            "*.c",
            "*.h",
            "*.py",
            "*.json",
        ],
        "progress_categories": [
            {"id": lib, "name": lib} for lib in LIBS
        ] + [
            {"id": cfg, "name": cfg.capitalize()} for cfg in CONFIGS
        ],
        "units": objdiff_units,
    }
    with open(ROOT / "objdiff.json", "w", encoding="utf-8") as f:
        json.dump(objdiff_config, f, indent=2)
        f.write("\n")

    for lib in missing_targets:
        print(f"warning: no target objects found for '{lib}' in baserom/<cfg>/{lib}/", file=sys.stderr)


if __name__ == "__main__":
    main()
